name: server_communication
description: Server Communication
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.64.1 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+15
  http: ^0.11.0
  jsonpadding: ^1.0.1
  stream_transform: ^0.0.5

dev_dependencies:
  build_runner: ^0.8.10
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
